#!/bin/bash
clear

export RED='\033[0;31m'
export GRAY="\e[1;30m"
export BLUE="\033[36m"
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BG='\033[44m'
export NC='\033[0m'

export ERROR="[${RED} ERROR ${NC}]";
export INFO="[${YELLOW} INFO ${NC}]";
export OKEY="[${GREEN} OKEY ${NC}]";
export PENDING="[${YELLOW} PENDING ${NC}]";
export SEND="[${YELLOW} SEND ${NC}]";
export RECEIVE="[${YELLOW} RECEIVE ${NC}]";

export IP=$(curl -sS ifconfig.me)

clear
echo -e "\033[0;36m╔======================================================╗${NC}"  
echo -e "\033[0;36m|${NC}\033[0;33m${bold}     _    ${NC}\033[0;34m${bold} ____ ${NC}${bold} _               ${NC}${bold}  _                 ${NC} \033[0;36m${bold}|${NC}" 
echo -e "\033[0;36m|${NC}\033[0;33m${bold}    | |___${NC}\033[0;34m${bold}|  _  ${NC}${bold}| |__ ${NC}\033[0;31m${bold}  __ _${NC}${bold} _ __ | |_${NC}\033[0;31m${bold} ___ ${NC}${bold} _ __ ___  ${NC}\033[0;36m${bold}|${NC}"
echo -e "\033[0;36m|${NC}\033[0;33m${bold} _  | / __${NC}\033[0;34m${bold}| |_) ${NC}${bold}|  _ |${NC}\033[0;31m${bold} / _  ${NC}${bold}|  _ \| __${NC}\033[0;31m${bold}/ _  ${NC}${bold}|  _   _ \ ${NC}\033[0;36m${bold}|${NC}"
echo -e "\033[0;36m|${NC}\033[0;33m${bold}| |_| \__ ${NC}\033[0;34m${bold}\  __/${NC}${bold}| | | ${NC}\033[0;31m${bold}| (_| ${NC}${bold}| | | | ||${NC}\033[0;31m${bold} (_) ${NC}${bold}| | | | | |${NC}\033[0;36m${bold}|${NC}"
echo -e "\033[0;36m|${NC}\033[0;33m${bold} \___/|___${NC}\033[0;34m${bold}/_|   ${NC}${bold}|_| |_${NC}\033[0;31m${bold}|\__,_${NC}${bold}|_| |_|\__${NC}\033[0;31m${bold}\___/${NC}${bold}|_| |_| |_|${NC}\033[0;36m${bold}|${NC}"
echo -e "\033[0;36m╚======================================================╝${NC}"
echo -e " ${BLUE}•────────────────────────────────────────────────────•${NC}"
sudo passwd root
sudo apt install curl -y
sudo apt update && sudo apt upgrade -y
sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
service sshd restart
echo -e "$INFO Successfully , Try Login Using 'root' Users"
echo -e "$BLUE•────────────────────────────────────────────────────•$NC"
echo -e ""
read -n 1 -s -r -p "  Press any key to reboot"
reboot
